# Generated by Django 3.0 on 2020-05-13 00:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=1000)),
                ('langue', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('sujet', models.CharField(max_length=50)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('reponse', models.TextField()),
                ('langue', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pre_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefr', models.CharField(max_length=50)),
                ('namear', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('date', models.DateField(default=0, max_length=20)),
                ('text', models.TextField()),
                ('langue', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefr', models.CharField(max_length=50)),
                ('namear', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefr', models.CharField(max_length=50)),
                ('namear', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text="url de la video  doit etre adapter a l'integration", max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('langue', models.CharField(default=0, max_length=10)),
                ('pre_post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.pre_post')),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('pre_post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.pre_post')),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('url', models.FileField(upload_to='')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('langue', models.CharField(default=0, max_length=10)),
                ('pre_post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.pre_post')),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('langue', models.CharField(default=0, max_length=10)),
                ('pre_post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.pre_post')),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('text', models.TextField()),
                ('langue', models.CharField(default=0, max_length=10)),
                ('pre_post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.pre_post')),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Acctualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('media', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('text', models.TextField()),
                ('langue', models.CharField(default=0, max_length=10)),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
            ],
        ),
    ]
