# Generated by Django 3.0.6 on 2020-05-05 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pre_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, help_text="name.extention ex image.jpg")),
                ('url', models.ImageField(null=True,blank=True)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.FileField()),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('text', models.TextField()),
                ('pre_post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.pre_post')),
                ('field', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Acctualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=100)),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('text', models.TextField()),
                ('secteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='odcoapp.Secteur')),
            ],
        ),

        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateField(default=0, max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
