# Generated by Django 3.0 on 2020-05-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odcoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
