# Generated by Django 3.0 on 2020-05-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odcoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('sujet', models.CharField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='assistance',
            old_name='field',
            new_name='secteur',
        ),
    ]
